declare -A countries
countries[1]="Australia"
countries[2]="Austria"
countries[3]="Bangladesh"
countries[4]="Belarus"
countries[5]="Belgium"
countries[6]="Bosnia_and_Herzegovina"
countries[7]="Brazil"
countries[8]="Bulgaria"
countries[9]="Canada"
countries[10]="Chile"
countries[11]="China"
countries[12]="Colombia"
countries[13]="Croatia"
countries[14]="Czechia"
countries[15]="Denmark"
countries[16]="Ecuador"
countries[17]="Finland"
countries[18]="France"
countries[19]="Georgia"
countries[20]="Germany"
countries[21]="Greece"
countries[22]="Hong_Kong"
countries[23]="Hungary"
countries[24]="Iceland"
countries[25]="India"
countries[26]="Indonesia"
countries[27]="Iran"
countries[28]="Ireland"
countries[29]="Israel"
countries[30]="Italy"
countries[31]="Japan"
countries[32]="Kazakhstan"
countries[33]="Kenya"
countries[34]="Latvia"
countries[35]="Lithuania"
countries[36]="Luxembourg"
countries[37]="Netherlands"
countries[38]="New_Caledonia"
countries[39]="New_Zealand"
countries[40]="North_Macedonia"
countries[41]="Norway"
countries[42]="Paraguay"
countries[43]="Philippines"
countries[44]="Poland"
countries[45]="Portugal"
countries[46]="Romania"
countries[47]="Russia"
countries[48]="Serbia"
countries[49]="Singapore"
countries[50]="Slovakia"
countries[51]="Slovenia"
countries[52]="South_Africa"
countries[53]="South_Korea"
countries[54]="Spain"
countries[55]="Sweden"
countries[56]="Switzerland"
countries[57]="Taiwan"
countries[58]="Thailand"
countries[59]="Turkey"
countries[60]="Ukraine"
countries[61]="United_Kingdom"
countries[62]="United_States"
countries[63]="Vietnam"

declare -A country_codes
country_codes[1]="AU"
country_codes[2]="AT"
country_codes[3]="BD"
country_codes[4]="BY"
country_codes[5]="BE"
country_codes[6]="BA"
country_codes[7]="BR"
country_codes[8]="BG"
country_codes[9]="CA"
country_codes[10]="CL"
country_codes[11]="CN"
country_codes[12]="CO"
country_codes[13]="HR"
country_codes[14]="CZ"
country_codes[15]="DK"
country_codes[16]="EC"
country_codes[17]="FI"
country_codes[18]="FR"
country_codes[19]="GE"
country_codes[20]="DE"
country_codes[21]="GR"
country_codes[22]="HK"
country_codes[23]="HU"
country_codes[24]="IS"
country_codes[25]="IN"
country_codes[26]="ID"
country_codes[27]="IR"
country_codes[28]="IE"
country_codes[29]="IL"
country_codes[30]="IT"
country_codes[31]="JP"
country_codes[32]="KZ"
country_codes[33]="KE"
country_codes[34]="LV"
country_codes[35]="LT"
country_codes[36]="LU"
country_codes[37]="NL"
country_codes[38]="NC"
country_codes[39]="NZ"
country_codes[40]="MK"
country_codes[41]="NO"
country_codes[42]="PY"
country_codes[43]="PH"
country_codes[44]="PL"
country_codes[45]="PT"
country_codes[46]="RO"
country_codes[47]="RU"
country_codes[48]="RS"
country_codes[49]="SG"
country_codes[50]="SK"
country_codes[51]="SI"
country_codes[52]="ZA"
country_codes[53]="KR"
country_codes[54]="ES"
country_codes[55]="SE"
country_codes[56]="CH"
country_codes[57]="TW"
country_codes[58]="TH"
country_codes[59]="TR"
country_codes[60]="UA"
country_codes[61]="GB"
country_codes[62]="US"
country_codes[63]="VN"

selectMirrorRegions() {
    checklist=""
    for i in {1..63}
    do
        checklist="$checklist $i ${countries[$i]} off"
    done

    mirror_regions=$(dialog --stdout --checklist "Choose Mirror Regions:" 25 40 15 $checklist)
    if [[ -z "${mirror_regions// }" ]]; then
        selectMirrorRegions
    fi
}

createMirrorList() {
    selectMirrorRegions

    args=""
    for i in $mirror_regions
    do
        echo "$i"
        args="$args --country ${country_codes[$i]}"
    done


    cmd="reflector $args --age 12 --protocol https --sort rate --save /etc/pacman.d/mirrorlist"
    dialog --infobox "Searching the best mirror in given regions... " 5 50; eval $cmd
}
